### ISSUE TITLE
Decision on which container registry to use

### ISSUE THREAD

**Issue by bajo1207** [bajo1207/piggymetrics#4]
We need to decide between Docker Hub and AWS ECR

**Comment by vijayakumarbathini** [comment]
**DockerHub**
If you have used Docker containers, then you probably know about DockerHub. Being the default registry service in the docker engine, it is the most widely used. DockerHub’s collaboration model is similar to that of GitHub. You can create organizations and also add individual collaborators to each repository. DockerHub provides major features like image repository management, webhooks, organizations, GitHub, and BitBucket integration with automated builds etc.

Pros:

Uses a very familiar collaboration model as GitHub, therefore being very easy to use, especially for GitHub users
Provides public and private repositories
Quickly creates organizations, add users or create groups of users to collaborate with your repositories.
Allows users to set permissions to restrict access or set different levels like read, ride and admin to different users.
Fairly inexpensive with usage based pricing.
Security scanning available on additional cost.  
Cons:

Lacks fine grain access control.
Does not provide any insight into the registry usage.
Lacks LDAP, SAML, and OAuth support.
Registry performance can be inconsistent.


**Amazon EC2 Registry**
Amazon EC2 Container Registry (ECR) is a fully managed container registry by AWS that offers very fine grained permissions and access control via AWS Identity and Access Management (IAM). Amazon ECR is integrated with Amazon EC2 Container Service (ECS), thus simplifying development to production workflow. Amazon ECR eliminates the need to operate your own container repositories or worry about scaling the underlying infrastructure. Amazon ECR hosts your images in a highly available and scalable architecture, allowing you to reliably deploy containers for your applications.

Pros:

Familiar to AWS users and easy to use.
Highly secure as policies can be configured to manage permissions and control access to user’s images using AWS IAM users and roles without having to manage credentials directly on EC2 instances.
No upfront fees or commitments. You pay only for the amount of data you store in your repositories and data transferred to the Internet.
Tight integration with Amazon ECS and the Docker CLI, allowing you to simplify your development and production workflows.  
Cons:

Lack of insight into registry usage.
Difficult to use with docker client as it requires creating a temporary token.
Potentially expensive if the containers being deployed are not in AWS.

**Comment by bajo1207** [comment]
Thank you for a good insight on the difference between Docker Hub and AWS ECR. We have landed on ECR.
