### ISSUE TITLE
Create Sign In API

### ISSUE THREAD

**Issue by bajo1207** [bajo1207/piggymetrics#6]
Create sign in API

**Comment by jblossey** [comment]
@bajo1207 please specify what you mean with "sign-in API"

**Comment by bajo1207** [comment]
We need to use the "Connect With PayPal API" to sign in to piggy metrics. This Issue serves to cover the technical aspect of the implementation, whereas the #5 describes the UI aspect. https://developer.paypal.com/docs/connect-with-paypal/

Both this and issue #5 are linked to the user story:
https://app.clubhouse.io/bajo1207/story/26/sign-in-button

**Comment by jblossey** [comment]
Then this annotation fits here better:
**Also think about #16 when implementing this.**

**Comment by jblossey** [comment]
I will assign this issue to me as i just finished #10 and stumbled across some implementation details that demand refactoring of new code from PR #21 after this issues has been closed successfully.
