### ISSUE TITLE
Reach consensus on underlying Python Framework

### ISSUE THREAD

**Issue by jblossey** [bajo1207/piggymetrics#8]
Current candidates are:
- [Flask](https://palletsprojects.com/p/flask/)
- [Django](https://www.djangoproject.com)
- [Falcon](https://falconframework.org)
- [CherryPy](https://cherrypy.org)
- [Appier](http://appier.hive.pt/)
- [Bottle](https://bottlepy.org/docs/dev/)
_All taken from [WSGI.org](https://wsgi.readthedocs.io/en/latest/frameworks.html)_

**Comment by jblossey** [comment]
# Flask
- License: BSD-3-Clause
- Wrapper around _Werkzeug_ and _Jinja_
- Good exhaustive [documentation](https://flask.palletsprojects.com/en/1.1.x/)
- Supports Python 3 & 2
- Documented Deployment option to [AWS Elastic Beanstalk](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create-deploy-python-flask.html) for possible increased flexibility (?)
- Very easy [routing](https://flask.palletsprojects.com/en/1.1.x/quickstart/#routing)
- Very easy [HTTP method](https://flask.palletsprojects.com/en/1.1.x/quickstart/#http-methods) (and thus REST) handling
- Built-in abilities to easily manage [Cookies](https://flask.palletsprojects.com/en/1.1.x/quickstart/#cookies), [requests](https://flask.palletsprojects.com/en/1.1.x/quickstart/#accessing-request-data) & [responses](https://flask.palletsprojects.com/en/1.1.x/quickstart/#about-responses)
- Regarding the Paypal API -> [APIs w/ JSON](https://flask.palletsprojects.com/en/1.1.x/quickstart/#apis-with-json) feature
- Built-in [Session management](https://flask.palletsprojects.com/en/1.1.x/quickstart/#sessions) (unknown of the session management in Piggymetrics this can be useful)
- Built-in [logger](https://flask.palletsprojects.com/en/1.1.x/quickstart/#logging)

**Comment by jblossey** [comment]
# Django
- License: special Django license
- all of the above (except Werkzeug/Jinja Wrapper, AWS EB Deploy, and Django seems overall more complex but also more customizable) 
- Additional feats:
    - [Pagination](https://docs.djangoproject.com/en/3.0/topics/pagination/) (Depending on how much visual complexity we want to include)
    - [Enhanced Security](https://docs.djangoproject.com/en/3.0/topics/security/) measures (We are dealing with personal financial info after all)
    - [Signals](https://docs.djangoproject.com/en/3.0/topics/signals/) for remote communication/calls between parts of the website 
    - Own [test suite](https://docs.djangoproject.com/en/3.0/topics/testing/)
    - Handy [shortcut functions](https://docs.djangoproject.com/en/3.0/topics/http/shortcuts/#module-django.shortcuts)

**Comment by jblossey** [comment]
# Falcon
- License: Apache 2.0
- Very minimalistic
- Does not implement any HTTP features
- Supports Unittest and Pytest
- Supports before and after hooks natively
- Very easy REST implementation via inset on_get/post/put... methods (see [routing](https://falcon.readthedocs.io/en/stable/api/routing.html#routing))
- highly customizable

**Comment by jblossey** [comment]
# CherryPy
- License: BSD-3-Clause
- Object-oriented
- Very easy [RESTing](https://docs.cherrypy.org/en/latest/tutorials.html#tutorial-7-give-us-a-rest)
- [AJAX](https://docs.cherrypy.org/en/latest/tutorials.html#tutorial-8-make-it-smoother-with-ajax)
- Distinction of [dispatchers](https://docs.cherrypy.org/en/latest/extend.html#dispatchers) and [tools](https://docs.cherrypy.org/en/latest/extend.html#tools)
- [plugins](https://docs.cherrypy.org/en/latest/extend.html#busplugins) for functions outside of the request life-cycle
- Supports Pytest and Codecoverage natively
- native logger
- session/cookie handling
- [easy startup configuration via simple JSON file](https://docs.cherrypy.org/en/latest/basics.html#per-application-configuration)
- Native Methods for JSON handling
- [Advanced](https://docs.cherrypy.org/en/latest/advanced.html#):
    - Advanced RESTful Style dispatching
    - Streaming
    - Signals
    - WSGI support
- much more...

**Comment by jblossey** [comment]
# Appier
- License: Apache 2.0
- Object-oriented
- explicit async/await structure (needs ASGI compliant server)
- Automatic JSON response encoding
- Easy [configuration](https://appier.hive.pt/doc/configuration.md) via reserved config variables (comparable to globals in Javascript)
- Easy [re-routing](https://appier.hive.pt/doc/controllers.md) of I/O
- Built-in [event handling](https://appier.hive.pt/doc/events.md) and [logging](https://appier.hive.pt/doc/logging.md)

**Comment by jblossey** [comment]
# Bottle
- License: MIT
- From the Site:
> - **Routing:** Requests to function-call mapping with support for clean and dynamic URLs.
> - **Templates:** Fast and pythonic built-in template engine and support for mako, jinja2 and cheetah templates.
> - **Utilities:** Convenient access to form data, file uploads, cookies, headers and other HTTP-related metadata.
> - **Server:** Built-in HTTP development server and support for paste, fapws3, bjoern, gae, cherrypy or any other WSGI capable HTTP server.
- [Dynamic Routing](https://bottlepy.org/docs/0.12/tutorial.html#dynamic-routes) via Regex
- [Easy REST setup](https://bottlepy.org/docs/0.12/tutorial.html#http-request-methods)

**Comment by jblossey** [comment]
I would personally prefer:

1. CherryPy
2. Flask
3. Falcon

**Comment by AndreasSpateneder** [comment]
After sprint meeting we decided to use CherryPy as the project Framework. It is a lightweight framework which has a suitible complexity for this project.
